type Opt = { value: string; label: string };

function tz(zone: string): Opt {
  return { value: zone, label: zone.replace(/_/g, ' ') };
}

// ─── IANA Timezones ───────────────────────────────────────────────────────────
// All canonical IANA timezone identifiers, sorted by region then city.
export const TIMEZONES: Opt[] = [
  // Africa
  tz('Africa/Abidjan'),
  tz('Africa/Accra'),
  tz('Africa/Addis_Ababa'),
  tz('Africa/Algiers'),
  tz('Africa/Asmara'),
  tz('Africa/Bamako'),
  tz('Africa/Bangui'),
  tz('Africa/Banjul'),
  tz('Africa/Bissau'),
  tz('Africa/Blantyre'),
  tz('Africa/Brazzaville'),
  tz('Africa/Bujumbura'),
  tz('Africa/Cairo'),
  tz('Africa/Casablanca'),
  tz('Africa/Ceuta'),
  tz('Africa/Conakry'),
  tz('Africa/Dakar'),
  tz('Africa/Dar_es_Salaam'),
  tz('Africa/Djibouti'),
  tz('Africa/Douala'),
  tz('Africa/El_Aaiun'),
  tz('Africa/Freetown'),
  tz('Africa/Gaborone'),
  tz('Africa/Harare'),
  tz('Africa/Johannesburg'),
  tz('Africa/Juba'),
  tz('Africa/Kampala'),
  tz('Africa/Khartoum'),
  tz('Africa/Kigali'),
  tz('Africa/Kinshasa'),
  tz('Africa/Lagos'),
  tz('Africa/Libreville'),
  tz('Africa/Lome'),
  tz('Africa/Luanda'),
  tz('Africa/Lubumbashi'),
  tz('Africa/Lusaka'),
  tz('Africa/Malabo'),
  tz('Africa/Maputo'),
  tz('Africa/Maseru'),
  tz('Africa/Mbabane'),
  tz('Africa/Mogadishu'),
  tz('Africa/Monrovia'),
  tz('Africa/Nairobi'),
  tz('Africa/Ndjamena'),
  tz('Africa/Niamey'),
  tz('Africa/Nouakchott'),
  tz('Africa/Ouagadougou'),
  tz('Africa/Porto-Novo'),
  tz('Africa/Sao_Tome'),
  tz('Africa/Tripoli'),
  tz('Africa/Tunis'),
  tz('Africa/Windhoek'),
  // America
  tz('America/Adak'),
  tz('America/Anchorage'),
  tz('America/Anguilla'),
  tz('America/Antigua'),
  tz('America/Araguaina'),
  tz('America/Argentina/Buenos_Aires'),
  tz('America/Argentina/Catamarca'),
  tz('America/Argentina/Cordoba'),
  tz('America/Argentina/Jujuy'),
  tz('America/Argentina/La_Rioja'),
  tz('America/Argentina/Mendoza'),
  tz('America/Argentina/Rio_Gallegos'),
  tz('America/Argentina/Salta'),
  tz('America/Argentina/San_Juan'),
  tz('America/Argentina/San_Luis'),
  tz('America/Argentina/Tucuman'),
  tz('America/Argentina/Ushuaia'),
  tz('America/Aruba'),
  tz('America/Asuncion'),
  tz('America/Atikokan'),
  tz('America/Bahia'),
  tz('America/Bahia_Banderas'),
  tz('America/Barbados'),
  tz('America/Belem'),
  tz('America/Belize'),
  tz('America/Blanc-Sablon'),
  tz('America/Boa_Vista'),
  tz('America/Bogota'),
  tz('America/Boise'),
  tz('America/Cambridge_Bay'),
  tz('America/Campo_Grande'),
  tz('America/Cancun'),
  tz('America/Caracas'),
  tz('America/Cayenne'),
  tz('America/Cayman'),
  tz('America/Chicago'),
  tz('America/Chihuahua'),
  tz('America/Costa_Rica'),
  tz('America/Creston'),
  tz('America/Cuiaba'),
  tz('America/Curacao'),
  tz('America/Danmarkshavn'),
  tz('America/Dawson'),
  tz('America/Dawson_Creek'),
  tz('America/Denver'),
  tz('America/Detroit'),
  tz('America/Dominica'),
  tz('America/Edmonton'),
  tz('America/Eirunepe'),
  tz('America/El_Salvador'),
  tz('America/Fortaleza'),
  tz('America/Glace_Bay'),
  tz('America/Goose_Bay'),
  tz('America/Grand_Turk'),
  tz('America/Grenada'),
  tz('America/Guadeloupe'),
  tz('America/Guatemala'),
  tz('America/Guayaquil'),
  tz('America/Guyana'),
  tz('America/Halifax'),
  tz('America/Havana'),
  tz('America/Hermosillo'),
  tz('America/Indiana/Indianapolis'),
  tz('America/Indiana/Knox'),
  tz('America/Indiana/Marengo'),
  tz('America/Indiana/Petersburg'),
  tz('America/Indiana/Tell_City'),
  tz('America/Indiana/Vevay'),
  tz('America/Indiana/Vincennes'),
  tz('America/Indiana/Winamac'),
  tz('America/Inuvik'),
  tz('America/Iqaluit'),
  tz('America/Jamaica'),
  tz('America/Juneau'),
  tz('America/Kentucky/Louisville'),
  tz('America/Kentucky/Monticello'),
  tz('America/Kralendijk'),
  tz('America/La_Paz'),
  tz('America/Lima'),
  tz('America/Los_Angeles'),
  tz('America/Lower_Princes'),
  tz('America/Maceio'),
  tz('America/Managua'),
  tz('America/Manaus'),
  tz('America/Marigot'),
  tz('America/Martinique'),
  tz('America/Matamoros'),
  tz('America/Mazatlan'),
  tz('America/Menominee'),
  tz('America/Merida'),
  tz('America/Metlakatla'),
  tz('America/Mexico_City'),
  tz('America/Miquelon'),
  tz('America/Moncton'),
  tz('America/Monterrey'),
  tz('America/Montevideo'),
  tz('America/Montserrat'),
  tz('America/Nassau'),
  tz('America/New_York'),
  tz('America/Nipigon'),
  tz('America/Nome'),
  tz('America/Noronha'),
  tz('America/North_Dakota/Beulah'),
  tz('America/North_Dakota/Center'),
  tz('America/North_Dakota/New_Salem'),
  tz('America/Ojinaga'),
  tz('America/Panama'),
  tz('America/Pangnirtung'),
  tz('America/Paramaribo'),
  tz('America/Phoenix'),
  tz('America/Port-au-Prince'),
  tz('America/Port_of_Spain'),
  tz('America/Porto_Velho'),
  tz('America/Puerto_Rico'),
  tz('America/Punta_Arenas'),
  tz('America/Rainy_River'),
  tz('America/Rankin_Inlet'),
  tz('America/Recife'),
  tz('America/Regina'),
  tz('America/Resolute'),
  tz('America/Rio_Branco'),
  tz('America/Santarem'),
  tz('America/Santiago'),
  tz('America/Santo_Domingo'),
  tz('America/Sao_Paulo'),
  tz('America/Scoresbysund'),
  tz('America/Sitka'),
  tz('America/St_Barthelemy'),
  tz('America/St_Johns'),
  tz('America/St_Kitts'),
  tz('America/St_Lucia'),
  tz('America/St_Thomas'),
  tz('America/St_Vincent'),
  tz('America/Swift_Current'),
  tz('America/Tegucigalpa'),
  tz('America/Thule'),
  tz('America/Thunder_Bay'),
  tz('America/Tijuana'),
  tz('America/Toronto'),
  tz('America/Tortola'),
  tz('America/Vancouver'),
  tz('America/Whitehorse'),
  tz('America/Winnipeg'),
  tz('America/Yakutat'),
  tz('America/Yellowknife'),
  // Antarctica
  tz('Antarctica/Casey'),
  tz('Antarctica/Davis'),
  tz('Antarctica/DumontDUrville'),
  tz('Antarctica/Macquarie'),
  tz('Antarctica/Mawson'),
  tz('Antarctica/McMurdo'),
  tz('Antarctica/Palmer'),
  tz('Antarctica/Rothera'),
  tz('Antarctica/Syowa'),
  tz('Antarctica/Troll'),
  tz('Antarctica/Vostok'),
  // Arctic
  tz('Arctic/Longyearbyen'),
  // Asia
  tz('Asia/Aden'),
  tz('Asia/Almaty'),
  tz('Asia/Amman'),
  tz('Asia/Anadyr'),
  tz('Asia/Aqtau'),
  tz('Asia/Aqtobe'),
  tz('Asia/Ashgabat'),
  tz('Asia/Atyrau'),
  tz('Asia/Baghdad'),
  tz('Asia/Bahrain'),
  tz('Asia/Baku'),
  tz('Asia/Bangkok'),
  tz('Asia/Barnaul'),
  tz('Asia/Beirut'),
  tz('Asia/Bishkek'),
  tz('Asia/Brunei'),
  tz('Asia/Chita'),
  tz('Asia/Choibalsan'),
  tz('Asia/Colombo'),
  tz('Asia/Damascus'),
  tz('Asia/Dhaka'),
  tz('Asia/Dili'),
  tz('Asia/Dubai'),
  tz('Asia/Dushanbe'),
  tz('Asia/Famagusta'),
  tz('Asia/Gaza'),
  tz('Asia/Hebron'),
  tz('Asia/Ho_Chi_Minh'),
  tz('Asia/Hong_Kong'),
  tz('Asia/Hovd'),
  tz('Asia/Irkutsk'),
  tz('Asia/Jakarta'),
  tz('Asia/Jayapura'),
  tz('Asia/Jerusalem'),
  tz('Asia/Kabul'),
  tz('Asia/Kamchatka'),
  tz('Asia/Karachi'),
  tz('Asia/Kathmandu'),
  tz('Asia/Khandyga'),
  tz('Asia/Kolkata'),
  tz('Asia/Krasnoyarsk'),
  tz('Asia/Kuala_Lumpur'),
  tz('Asia/Kuching'),
  tz('Asia/Kuwait'),
  tz('Asia/Macau'),
  tz('Asia/Magadan'),
  tz('Asia/Makassar'),
  tz('Asia/Manila'),
  tz('Asia/Muscat'),
  tz('Asia/Nicosia'),
  tz('Asia/Novokuznetsk'),
  tz('Asia/Novosibirsk'),
  tz('Asia/Omsk'),
  tz('Asia/Oral'),
  tz('Asia/Phnom_Penh'),
  tz('Asia/Pontianak'),
  tz('Asia/Pyongyang'),
  tz('Asia/Qatar'),
  tz('Asia/Qostanay'),
  tz('Asia/Qyzylorda'),
  tz('Asia/Riyadh'),
  tz('Asia/Sakhalin'),
  tz('Asia/Samarkand'),
  tz('Asia/Seoul'),
  tz('Asia/Shanghai'),
  tz('Asia/Singapore'),
  tz('Asia/Srednekolymsk'),
  tz('Asia/Taipei'),
  tz('Asia/Tashkent'),
  tz('Asia/Tbilisi'),
  tz('Asia/Tehran'),
  tz('Asia/Thimphu'),
  tz('Asia/Tokyo'),
  tz('Asia/Tomsk'),
  tz('Asia/Ulaanbaatar'),
  tz('Asia/Urumqi'),
  tz('Asia/Ust-Nera'),
  tz('Asia/Vientiane'),
  tz('Asia/Vladivostok'),
  tz('Asia/Yakutsk'),
  tz('Asia/Yangon'),
  tz('Asia/Yekaterinburg'),
  tz('Asia/Yerevan'),
  // Atlantic
  tz('Atlantic/Azores'),
  tz('Atlantic/Bermuda'),
  tz('Atlantic/Canary'),
  tz('Atlantic/Cape_Verde'),
  tz('Atlantic/Faroe'),
  tz('Atlantic/Madeira'),
  tz('Atlantic/Reykjavik'),
  tz('Atlantic/South_Georgia'),
  tz('Atlantic/St_Helena'),
  tz('Atlantic/Stanley'),
  // Australia
  tz('Australia/Adelaide'),
  tz('Australia/Brisbane'),
  tz('Australia/Broken_Hill'),
  tz('Australia/Darwin'),
  tz('Australia/Eucla'),
  tz('Australia/Hobart'),
  tz('Australia/Lindeman'),
  tz('Australia/Lord_Howe'),
  tz('Australia/Melbourne'),
  tz('Australia/Perth'),
  tz('Australia/Sydney'),
  // Europe
  tz('Europe/Amsterdam'),
  tz('Europe/Andorra'),
  tz('Europe/Astrakhan'),
  tz('Europe/Athens'),
  tz('Europe/Belgrade'),
  tz('Europe/Berlin'),
  tz('Europe/Bratislava'),
  tz('Europe/Brussels'),
  tz('Europe/Bucharest'),
  tz('Europe/Budapest'),
  tz('Europe/Busingen'),
  tz('Europe/Chisinau'),
  tz('Europe/Copenhagen'),
  tz('Europe/Dublin'),
  tz('Europe/Gibraltar'),
  tz('Europe/Guernsey'),
  tz('Europe/Helsinki'),
  tz('Europe/Isle_of_Man'),
  tz('Europe/Istanbul'),
  tz('Europe/Jersey'),
  tz('Europe/Kaliningrad'),
  tz('Europe/Kiev'),
  tz('Europe/Kirov'),
  tz('Europe/Lisbon'),
  tz('Europe/Ljubljana'),
  tz('Europe/London'),
  tz('Europe/Luxembourg'),
  tz('Europe/Madrid'),
  tz('Europe/Malta'),
  tz('Europe/Mariehamn'),
  tz('Europe/Minsk'),
  tz('Europe/Monaco'),
  tz('Europe/Moscow'),
  tz('Europe/Nicosia'),
  tz('Europe/Oslo'),
  tz('Europe/Paris'),
  tz('Europe/Podgorica'),
  tz('Europe/Prague'),
  tz('Europe/Riga'),
  tz('Europe/Rome'),
  tz('Europe/Samara'),
  tz('Europe/San_Marino'),
  tz('Europe/Sarajevo'),
  tz('Europe/Saratov'),
  tz('Europe/Simferopol'),
  tz('Europe/Skopje'),
  tz('Europe/Sofia'),
  tz('Europe/Stockholm'),
  tz('Europe/Tallinn'),
  tz('Europe/Tirane'),
  tz('Europe/Ulyanovsk'),
  tz('Europe/Uzhgorod'),
  tz('Europe/Vaduz'),
  tz('Europe/Vatican'),
  tz('Europe/Vienna'),
  tz('Europe/Vilnius'),
  tz('Europe/Volgograd'),
  tz('Europe/Warsaw'),
  tz('Europe/Zagreb'),
  tz('Europe/Zaporozhye'),
  tz('Europe/Zurich'),
  // Indian Ocean
  tz('Indian/Antananarivo'),
  tz('Indian/Chagos'),
  tz('Indian/Christmas'),
  tz('Indian/Cocos'),
  tz('Indian/Comoro'),
  tz('Indian/Kerguelen'),
  tz('Indian/Mahe'),
  tz('Indian/Maldives'),
  tz('Indian/Mauritius'),
  tz('Indian/Mayotte'),
  tz('Indian/Reunion'),
  // Pacific
  tz('Pacific/Apia'),
  tz('Pacific/Auckland'),
  tz('Pacific/Bougainville'),
  tz('Pacific/Chatham'),
  tz('Pacific/Chuuk'),
  tz('Pacific/Easter'),
  tz('Pacific/Efate'),
  tz('Pacific/Fakaofo'),
  tz('Pacific/Fiji'),
  tz('Pacific/Funafuti'),
  tz('Pacific/Galapagos'),
  tz('Pacific/Gambier'),
  tz('Pacific/Guadalcanal'),
  tz('Pacific/Guam'),
  tz('Pacific/Honolulu'),
  tz('Pacific/Kiritimati'),
  tz('Pacific/Kosrae'),
  tz('Pacific/Kwajalein'),
  tz('Pacific/Majuro'),
  tz('Pacific/Marquesas'),
  tz('Pacific/Midway'),
  tz('Pacific/Nauru'),
  tz('Pacific/Niue'),
  tz('Pacific/Norfolk'),
  tz('Pacific/Noumea'),
  tz('Pacific/Pago_Pago'),
  tz('Pacific/Palau'),
  tz('Pacific/Pitcairn'),
  tz('Pacific/Pohnpei'),
  tz('Pacific/Port_Moresby'),
  tz('Pacific/Rarotonga'),
  tz('Pacific/Saipan'),
  tz('Pacific/Tahiti'),
  tz('Pacific/Tarawa'),
  tz('Pacific/Tongatapu'),
  tz('Pacific/Wake'),
  tz('Pacific/Wallis'),
  // Universal
  { value: 'UTC', label: 'UTC' },
];

// ─── BCP 47 Locale Tags (localFormat) ────────────────────────────────────────
// Used by Node.js toLocaleString() for date/time formatting.
export const LOCALE_FORMATS: Opt[] = [
  { value: 'af-ZA', label: 'af-ZA — Afrikaans (South Africa)' },
  { value: 'am-ET', label: 'am-ET — Amharic (Ethiopia)' },
  { value: 'ar-AE', label: 'ar-AE — Arabic (UAE)' },
  { value: 'ar-BH', label: 'ar-BH — Arabic (Bahrain)' },
  { value: 'ar-DZ', label: 'ar-DZ — Arabic (Algeria)' },
  { value: 'ar-EG', label: 'ar-EG — Arabic (Egypt)' },
  { value: 'ar-IQ', label: 'ar-IQ — Arabic (Iraq)' },
  { value: 'ar-JO', label: 'ar-JO — Arabic (Jordan)' },
  { value: 'ar-KW', label: 'ar-KW — Arabic (Kuwait)' },
  { value: 'ar-LB', label: 'ar-LB — Arabic (Lebanon)' },
  { value: 'ar-LY', label: 'ar-LY — Arabic (Libya)' },
  { value: 'ar-MA', label: 'ar-MA — Arabic (Morocco)' },
  { value: 'ar-OM', label: 'ar-OM — Arabic (Oman)' },
  { value: 'ar-QA', label: 'ar-QA — Arabic (Qatar)' },
  { value: 'ar-SA', label: 'ar-SA — Arabic (Saudi Arabia)' },
  { value: 'ar-SY', label: 'ar-SY — Arabic (Syria)' },
  { value: 'ar-TN', label: 'ar-TN — Arabic (Tunisia)' },
  { value: 'ar-YE', label: 'ar-YE — Arabic (Yemen)' },
  { value: 'az-AZ', label: 'az-AZ — Azerbaijani (Azerbaijan)' },
  { value: 'be-BY', label: 'be-BY — Belarusian (Belarus)' },
  { value: 'bg-BG', label: 'bg-BG — Bulgarian (Bulgaria)' },
  { value: 'bn-BD', label: 'bn-BD — Bengali (Bangladesh)' },
  { value: 'bn-IN', label: 'bn-IN — Bengali (India)' },
  { value: 'bs-BA', label: 'bs-BA — Bosnian (Bosnia)' },
  { value: 'ca-ES', label: 'ca-ES — Catalan (Spain)' },
  { value: 'cs-CZ', label: 'cs-CZ — Czech (Czech Republic)' },
  { value: 'cy-GB', label: 'cy-GB — Welsh (United Kingdom)' },
  { value: 'da-DK', label: 'da-DK — Danish (Denmark)' },
  { value: 'de-AT', label: 'de-AT — German (Austria)' },
  { value: 'de-CH', label: 'de-CH — German (Switzerland)' },
  { value: 'de-DE', label: 'de-DE — German (Germany)' },
  { value: 'el-GR', label: 'el-GR — Greek (Greece)' },
  { value: 'en-AU', label: 'en-AU — English (Australia)' },
  { value: 'en-CA', label: 'en-CA — English (Canada)' },
  { value: 'en-GB', label: 'en-GB — English (United Kingdom)' },
  { value: 'en-IE', label: 'en-IE — English (Ireland)' },
  { value: 'en-IN', label: 'en-IN — English (India)' },
  { value: 'en-MY', label: 'en-MY — English (Malaysia)' },
  { value: 'en-NZ', label: 'en-NZ — English (New Zealand)' },
  { value: 'en-PH', label: 'en-PH — English (Philippines)' },
  { value: 'en-PK', label: 'en-PK — English (Pakistan)' },
  { value: 'en-SG', label: 'en-SG — English (Singapore)' },
  { value: 'en-US', label: 'en-US — English (United States)' },
  { value: 'en-ZA', label: 'en-ZA — English (South Africa)' },
  { value: 'es-AR', label: 'es-AR — Spanish (Argentina)' },
  { value: 'es-BO', label: 'es-BO — Spanish (Bolivia)' },
  { value: 'es-CL', label: 'es-CL — Spanish (Chile)' },
  { value: 'es-CO', label: 'es-CO — Spanish (Colombia)' },
  { value: 'es-CR', label: 'es-CR — Spanish (Costa Rica)' },
  { value: 'es-DO', label: 'es-DO — Spanish (Dominican Republic)' },
  { value: 'es-EC', label: 'es-EC — Spanish (Ecuador)' },
  { value: 'es-ES', label: 'es-ES — Spanish (Spain)' },
  { value: 'es-GT', label: 'es-GT — Spanish (Guatemala)' },
  { value: 'es-HN', label: 'es-HN — Spanish (Honduras)' },
  { value: 'es-MX', label: 'es-MX — Spanish (Mexico)' },
  { value: 'es-NI', label: 'es-NI — Spanish (Nicaragua)' },
  { value: 'es-PA', label: 'es-PA — Spanish (Panama)' },
  { value: 'es-PE', label: 'es-PE — Spanish (Peru)' },
  { value: 'es-PY', label: 'es-PY — Spanish (Paraguay)' },
  { value: 'es-SV', label: 'es-SV — Spanish (El Salvador)' },
  { value: 'es-UY', label: 'es-UY — Spanish (Uruguay)' },
  { value: 'es-VE', label: 'es-VE — Spanish (Venezuela)' },
  { value: 'et-EE', label: 'et-EE — Estonian (Estonia)' },
  { value: 'eu-ES', label: 'eu-ES — Basque (Spain)' },
  { value: 'fa-IR', label: 'fa-IR — Persian (Iran)' },
  { value: 'fi-FI', label: 'fi-FI — Finnish (Finland)' },
  { value: 'fil-PH', label: 'fil-PH — Filipino (Philippines)' },
  { value: 'fr-BE', label: 'fr-BE — French (Belgium)' },
  { value: 'fr-CA', label: 'fr-CA — French (Canada)' },
  { value: 'fr-CH', label: 'fr-CH — French (Switzerland)' },
  { value: 'fr-FR', label: 'fr-FR — French (France)' },
  { value: 'gl-ES', label: 'gl-ES — Galician (Spain)' },
  { value: 'gu-IN', label: 'gu-IN — Gujarati (India)' },
  { value: 'he-IL', label: 'he-IL — Hebrew (Israel)' },
  { value: 'hi-IN', label: 'hi-IN — Hindi (India)' },
  { value: 'hr-HR', label: 'hr-HR — Croatian (Croatia)' },
  { value: 'hu-HU', label: 'hu-HU — Hungarian (Hungary)' },
  { value: 'hy-AM', label: 'hy-AM — Armenian (Armenia)' },
  { value: 'id-ID', label: 'id-ID — Indonesian (Indonesia)' },
  { value: 'is-IS', label: 'is-IS — Icelandic (Iceland)' },
  { value: 'it-CH', label: 'it-CH — Italian (Switzerland)' },
  { value: 'it-IT', label: 'it-IT — Italian (Italy)' },
  { value: 'ja-JP', label: 'ja-JP — Japanese (Japan)' },
  { value: 'ka-GE', label: 'ka-GE — Georgian (Georgia)' },
  { value: 'kk-KZ', label: 'kk-KZ — Kazakh (Kazakhstan)' },
  { value: 'km-KH', label: 'km-KH — Khmer (Cambodia)' },
  { value: 'kn-IN', label: 'kn-IN — Kannada (India)' },
  { value: 'ko-KR', label: 'ko-KR — Korean (South Korea)' },
  { value: 'lo-LA', label: 'lo-LA — Lao (Laos)' },
  { value: 'lt-LT', label: 'lt-LT — Lithuanian (Lithuania)' },
  { value: 'lv-LV', label: 'lv-LV — Latvian (Latvia)' },
  { value: 'mk-MK', label: 'mk-MK — Macedonian (North Macedonia)' },
  { value: 'ml-IN', label: 'ml-IN — Malayalam (India)' },
  { value: 'mn-MN', label: 'mn-MN — Mongolian (Mongolia)' },
  { value: 'mr-IN', label: 'mr-IN — Marathi (India)' },
  { value: 'ms-BN', label: 'ms-BN — Malay (Brunei)' },
  { value: 'ms-MY', label: 'ms-MY — Malay (Malaysia)' },
  { value: 'ms-SG', label: 'ms-SG — Malay (Singapore)' },
  { value: 'mt-MT', label: 'mt-MT — Maltese (Malta)' },
  { value: 'my-MM', label: 'my-MM — Burmese (Myanmar)' },
  { value: 'nb-NO', label: 'nb-NO — Norwegian Bokmål (Norway)' },
  { value: 'ne-NP', label: 'ne-NP — Nepali (Nepal)' },
  { value: 'nl-BE', label: 'nl-BE — Dutch (Belgium)' },
  { value: 'nl-NL', label: 'nl-NL — Dutch (Netherlands)' },
  { value: 'pa-IN', label: 'pa-IN — Punjabi (India)' },
  { value: 'pa-PK', label: 'pa-PK — Punjabi (Pakistan)' },
  { value: 'pl-PL', label: 'pl-PL — Polish (Poland)' },
  { value: 'pt-BR', label: 'pt-BR — Portuguese (Brazil)' },
  { value: 'pt-PT', label: 'pt-PT — Portuguese (Portugal)' },
  { value: 'ro-RO', label: 'ro-RO — Romanian (Romania)' },
  { value: 'ru-RU', label: 'ru-RU — Russian (Russia)' },
  { value: 'si-LK', label: 'si-LK — Sinhala (Sri Lanka)' },
  { value: 'sk-SK', label: 'sk-SK — Slovak (Slovakia)' },
  { value: 'sl-SI', label: 'sl-SI — Slovenian (Slovenia)' },
  { value: 'sq-AL', label: 'sq-AL — Albanian (Albania)' },
  { value: 'sr-RS', label: 'sr-RS — Serbian (Serbia)' },
  { value: 'sv-FI', label: 'sv-FI — Swedish (Finland)' },
  { value: 'sv-SE', label: 'sv-SE — Swedish (Sweden)' },
  { value: 'sw-KE', label: 'sw-KE — Swahili (Kenya)' },
  { value: 'sw-TZ', label: 'sw-TZ — Swahili (Tanzania)' },
  { value: 'ta-IN', label: 'ta-IN — Tamil (India)' },
  { value: 'ta-LK', label: 'ta-LK — Tamil (Sri Lanka)' },
  { value: 'ta-MY', label: 'ta-MY — Tamil (Malaysia)' },
  { value: 'ta-SG', label: 'ta-SG — Tamil (Singapore)' },
  { value: 'te-IN', label: 'te-IN — Telugu (India)' },
  { value: 'th-TH', label: 'th-TH — Thai (Thailand)' },
  { value: 'tr-TR', label: 'tr-TR — Turkish (Turkey)' },
  { value: 'uk-UA', label: 'uk-UA — Ukrainian (Ukraine)' },
  { value: 'ur-PK', label: 'ur-PK — Urdu (Pakistan)' },
  { value: 'uz-UZ', label: 'uz-UZ — Uzbek (Uzbekistan)' },
  { value: 'vi-VN', label: 'vi-VN — Vietnamese (Vietnam)' },
  { value: 'zh-CN', label: 'zh-CN — Chinese Simplified (China)' },
  { value: 'zh-HK', label: 'zh-HK — Chinese Traditional (Hong Kong)' },
  { value: 'zh-SG', label: 'zh-SG — Chinese (Singapore)' },
  { value: 'zh-TW', label: 'zh-TW — Chinese Traditional (Taiwan)' },
  { value: 'zu-ZA', label: 'zu-ZA — Zulu (South Africa)' },
];

// ─── OpenAI Whisper Language Codes (ISO 639-1) ────────────────────────────────
// Passed to Whisper API as the `language` parameter for voice transcription.
export const WHISPER_LANGUAGES: Opt[] = [
  { value: 'af',  label: 'af — Afrikaans' },
  { value: 'am',  label: 'am — Amharic' },
  { value: 'ar',  label: 'ar — Arabic' },
  { value: 'as',  label: 'as — Assamese' },
  { value: 'az',  label: 'az — Azerbaijani' },
  { value: 'ba',  label: 'ba — Bashkir' },
  { value: 'be',  label: 'be — Belarusian' },
  { value: 'bg',  label: 'bg — Bulgarian' },
  { value: 'bn',  label: 'bn — Bengali' },
  { value: 'bo',  label: 'bo — Tibetan' },
  { value: 'br',  label: 'br — Breton' },
  { value: 'bs',  label: 'bs — Bosnian' },
  { value: 'ca',  label: 'ca — Catalan' },
  { value: 'cs',  label: 'cs — Czech' },
  { value: 'cy',  label: 'cy — Welsh' },
  { value: 'da',  label: 'da — Danish' },
  { value: 'de',  label: 'de — German' },
  { value: 'el',  label: 'el — Greek' },
  { value: 'en',  label: 'en — English' },
  { value: 'es',  label: 'es — Spanish' },
  { value: 'et',  label: 'et — Estonian' },
  { value: 'eu',  label: 'eu — Basque' },
  { value: 'fa',  label: 'fa — Persian' },
  { value: 'fi',  label: 'fi — Finnish' },
  { value: 'fo',  label: 'fo — Faroese' },
  { value: 'fr',  label: 'fr — French' },
  { value: 'gl',  label: 'gl — Galician' },
  { value: 'gu',  label: 'gu — Gujarati' },
  { value: 'ha',  label: 'ha — Hausa' },
  { value: 'haw', label: 'haw — Hawaiian' },
  { value: 'he',  label: 'he — Hebrew' },
  { value: 'hi',  label: 'hi — Hindi' },
  { value: 'hr',  label: 'hr — Croatian' },
  { value: 'ht',  label: 'ht — Haitian Creole' },
  { value: 'hu',  label: 'hu — Hungarian' },
  { value: 'hy',  label: 'hy — Armenian' },
  { value: 'id',  label: 'id — Indonesian' },
  { value: 'is',  label: 'is — Icelandic' },
  { value: 'it',  label: 'it — Italian' },
  { value: 'ja',  label: 'ja — Japanese' },
  { value: 'jw',  label: 'jw — Javanese' },
  { value: 'ka',  label: 'ka — Georgian' },
  { value: 'kk',  label: 'kk — Kazakh' },
  { value: 'km',  label: 'km — Khmer' },
  { value: 'kn',  label: 'kn — Kannada' },
  { value: 'ko',  label: 'ko — Korean' },
  { value: 'la',  label: 'la — Latin' },
  { value: 'lb',  label: 'lb — Luxembourgish' },
  { value: 'ln',  label: 'ln — Lingala' },
  { value: 'lo',  label: 'lo — Lao' },
  { value: 'lt',  label: 'lt — Lithuanian' },
  { value: 'lv',  label: 'lv — Latvian' },
  { value: 'mg',  label: 'mg — Malagasy' },
  { value: 'mi',  label: 'mi — Maori' },
  { value: 'mk',  label: 'mk — Macedonian' },
  { value: 'ml',  label: 'ml — Malayalam' },
  { value: 'mn',  label: 'mn — Mongolian' },
  { value: 'mr',  label: 'mr — Marathi' },
  { value: 'ms',  label: 'ms — Malay' },
  { value: 'mt',  label: 'mt — Maltese' },
  { value: 'my',  label: 'my — Burmese' },
  { value: 'ne',  label: 'ne — Nepali' },
  { value: 'nl',  label: 'nl — Dutch' },
  { value: 'nn',  label: 'nn — Norwegian Nynorsk' },
  { value: 'no',  label: 'no — Norwegian' },
  { value: 'oc',  label: 'oc — Occitan' },
  { value: 'pa',  label: 'pa — Punjabi' },
  { value: 'pl',  label: 'pl — Polish' },
  { value: 'ps',  label: 'ps — Pashto' },
  { value: 'pt',  label: 'pt — Portuguese' },
  { value: 'ro',  label: 'ro — Romanian' },
  { value: 'ru',  label: 'ru — Russian' },
  { value: 'sa',  label: 'sa — Sanskrit' },
  { value: 'sd',  label: 'sd — Sindhi' },
  { value: 'si',  label: 'si — Sinhala' },
  { value: 'sk',  label: 'sk — Slovak' },
  { value: 'sl',  label: 'sl — Slovenian' },
  { value: 'sn',  label: 'sn — Shona' },
  { value: 'so',  label: 'so — Somali' },
  { value: 'sq',  label: 'sq — Albanian' },
  { value: 'sr',  label: 'sr — Serbian' },
  { value: 'su',  label: 'su — Sundanese' },
  { value: 'sv',  label: 'sv — Swedish' },
  { value: 'sw',  label: 'sw — Swahili' },
  { value: 'ta',  label: 'ta — Tamil' },
  { value: 'te',  label: 'te — Telugu' },
  { value: 'tg',  label: 'tg — Tajik' },
  { value: 'th',  label: 'th — Thai' },
  { value: 'tk',  label: 'tk — Turkmen' },
  { value: 'tl',  label: 'tl — Tagalog' },
  { value: 'tr',  label: 'tr — Turkish' },
  { value: 'tt',  label: 'tt — Tatar' },
  { value: 'uk',  label: 'uk — Ukrainian' },
  { value: 'ur',  label: 'ur — Urdu' },
  { value: 'uz',  label: 'uz — Uzbek' },
  { value: 'vi',  label: 'vi — Vietnamese' },
  { value: 'yi',  label: 'yi — Yiddish' },
  { value: 'yo',  label: 'yo — Yoruba' },
  { value: 'zh',  label: 'zh — Chinese' },
];
